parameters:
    tgorz_training.service.notification.class: Tgorz\TrainingBundle\Service\NotificationService
services:
    tgorz_notification:
        class: %tgorz_training.service.notification.class%
        arguments: ["@session"]
#    tgorz_training.example:
#        class: Tgorz\TrainingBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
