parameters:
    tgorz_training.service.notification.class: Tgorz\TrainingBundle\Service\NotificationService
#    tgorz_training.event_listentr.exception_listener.class: Tgorz\TrainingBundle\EventListener\ExceptionListener;
services:
    tgorz_notification:
        class: %tgorz_training.service.notification.class%
        arguments: ["@session"]
    tgorz_exeption_listener:
        class: Tgorz\TrainingBundle\EventListener\ExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
#    tgorz_exception_subscriber:
#        class: Tgorz\TrainingBundle\EventSubscriber\ExceptionSubscriber
#        tags:
#            - { name: kernel.event_subscriber }
    tgorz_training.subscriber.pre_update:
        class: Tgorz\TrainingBundle\EventSubscriber\PostUpdateSubscriber
        tags:
            - { name: doctrine.event_subscriber }
    tgorz_trainig.subscriber.test:
        class: Tgorz\TrainingBundle\EventSubscriber\TestSubscriber
        tags:
            - { name: kernel.event_subscriber, connection: default }

